{% set name = "openinference-instrumentation-dspy" %}
{% set version = "0.1.42" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation_dspy-{{ version }}.tar.gz
  sha256: e7e63d44808ec1ba1c728e7dc2b6a70a6328dfb3054dfe6a95c40a7a0bb9c419

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.12
    - opentelemetry-api
    - opentelemetry-instrumentation
    - opentelemetry-semantic-conventions
    - openinference-instrumentation >=0.1.12
    - openinference-semantic-conventions >=0.1.9
    - wrapt
    - typing-extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - openinference.instrumentation.dspy

about:
  summary: OpenInference DSPy Instrumentation
  home: https://github.com/Arize-ai/openinference
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michaelschiff
    - mikeldking
    - RogerHYang
    - axiomofjoy
    - anticorrelator
