{% set name = "openinference-instrumentation-dspy" %}
{% set version = "0.1.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation_dspy-{{ version }}.tar.gz
  sha256: 097c9cbad509eb1b984532a4046865fc7d5442791ef651193e2d7a03dafd5a1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.12
    - opentelemetry-api
    - opentelemetry-instrumentation
    - opentelemetry-semantic-conventions
    - openinference-instrumentation >=0.1.12
    - openinference-semantic-conventions >=0.1.9
    - wrapt
    - typing-extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - openinference.instrumentation.dspy

about:
  summary: OpenInference DSPy Instrumentation
  home: https://github.com/Arize-ai/openinference
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michaelschiff
    - mikeldking
    - RogerHYang
    - axiomofjoy
    - anticorrelator
